2 customizable channel data message
metaworking/channeld-ue-plugin pull request #11
Opened 2023-04-17 02:19 UTC by Augkit

- Added channel data editor for editing channel data schemata.
- Each channel type configured with a schema will generate a corresponding channel data proto message, channel data processor, and data.go.
- Separate blueprint scanning at code generation time into independent build cache functionality.

2023-04-24 03:59 UTC, indiest commented on Source/ChanneldEditor/ChanneldEditor.h
> +enum EChanneldLaunchResult : uint8
改为：采用bool返回值+ErrorString传参的形式

2023-04-24 03:59 UTC, indiest commented on Source/ChanneldEditor/ChanneldEditorCommands.cpp
> +	UI_COMMAND(OpenChannelDataEditorCommand, "Edit Channel Data Schema", "Open channel data schema editor", EUserInterfaceActionType::Button, FInputChord());
```suggestion
	UI_COMMAND(OpenChannelDataEditorCommand, "Edit Channel Data Schema...", "Open channel data schema editor", EUserInterfaceActionType::Button, FInputChord());
```
有二级界面，所以后面加...

2023-04-24 03:59 UTC, indiest commented on Source/ChanneldEditor/ChanneldEditorCommands.cpp
>  	UI_COMMAND(GenerateReplicatorCommand, "Generate Replication Code", "Generate replication code for all replicated actors", EUserInterfaceActionType::Button, FInputChord());
什么情况下会不编辑频道数据模型，但是需要重新编译？如果不存在这种情况，下拉菜单就不需要显示这个按钮。

2023-04-25 01:15 UTC, indiest commented on Docs/zh/add-replication.md
> +2. 找到`Spatial`频道，点击`Add`按钮，在展开的菜单中依次点击`ThirdPersonPlayerController`和`BP_TestActor`的资源引用。
这一步还没有开启空间频道，应该是在全局频道数据中添加这些类吧？

2023-04-25 01:19 UTC, indiest commented on Docs/zh/channel-data-schema.md
> +每种频道类型对应频道数据模型由若干频道数据状态组成。频道数据状态是指同步Actor、ActorComponent的状态。一个频道数据状态在一个频道数据中可以是单例的，也可以多例的。
这里的描述跟[基本概念](https://github.com/metaworking/channeld-ue-plugin/blob/master/Docs/zh/basic-concepts.md#%E9%A2%91%E9%81%93%E6%95%B0%E6%8D%AE%E4%B8%AD%E7%9A%84%E7%8A%B6%E6%80%81)中的状态描述有重复。建议这一节和上一节合并，并连接到基本描述中。

2023-04-25 01:23 UTC, indiest commented on Docs/zh/channel-data-schema.md
> +>通常GameState、worldSetting等在GamePlay开发过程中保持一个服务器仅一份实例单例的同步Actor时，该同步Actor的状态在频道数据模型为单例。
```suggestion
>GameState、WorldSetting等同步Actor在一个虚拟世界中仅存在一个实例，其在频道数据模型中应该为单例。
```

2023-04-25 01:28 UTC, indiest commented on Docs/zh/channel-data-schema.md
> +频道数据模型的定义是用json文件描述的，但是不推荐您直接对json文件进行修改，而是使用更加便捷的编辑器进行编辑。
尽量用“开发者”代替“您”。这里可以不需要代词。
```suggestion
频道数据模型的定义是用JSON格式描述的，储存在<项目相对路径>，但是不推荐直接对json文件进行修改，而是使用ChanneldUE内置的编辑器进行编辑。
```

2023-04-25 01:31 UTC, indiest commented on Docs/zh/channel-data-schema.md
> +### 更新同步Actor缓存
“同步Actor缓存”有点绕口——此处“同步”可能被理解成动词。建议此处统一术语为“同步缓存”（ReplicationCache / RepCache）

2023-04-25 01:31 UTC, indiest commented on Docs/zh/channel-data-schema.md
> +等待一段时间，当Unreal Engine编辑器右下角提示`Successfully updated rep actor cache`时，表示更新成功。
注意大小写，跟截图的内容统一。

2023-04-25 01:38 UTC, indiest commented on Docs/zh/channel-data-schema.md
> +![](../images/add_channel_data_type.png)
窗口的标题能否去掉EUW的前缀？

2023-04-25 01:39 UTC, indiest commented on Docs/zh/channel-data-schema.md
> +### 删除频道数据模型
删除整个频道数据模型，是否有弹框确认？

另外，所有编辑操作，是否接入了Undo/Redo的API？

2023-04-25 01:42 UTC, indiest commented on Docs/zh/channel-data-schema.md
> +![](../images/add_channel_data_state.png)
我自己使用下来的体验，就是棕色和绿色的高亮同时出现让我感到有些困惑。建议没有被鼠标选中处的高亮，采用同样的色相，但是更低的明度或饱和度。

2023-04-25 01:48 UTC, indiest commented on Docs/zh/channel-data-schema.md
> +>如果被删除的频道数据状态的子类或者组件的使用者是该数据频道模型的状态，那么需要先删除其子类或组件的使用者吃能将其自己删除。
```suggestion
>在删除某个状态前，需要先删除依赖它的状态，如子类或组件的状态。
```

2023-04-25 01:53 UTC, indiest commented on Docs/zh/channel-data-schema.md
> +* 导入频道数据模型
在导入或修改频道数据模型后，关闭编辑器或启动游戏时，如果检测到没有生成同步代码，应该提示用户。

2023-04-26 08:45 UTC, Augkit commented on Docs/zh/channel-data-schema.md
> +### 删除频道数据模型
实现了Undo/Redo

2023-04-28 07:32 UTC, indiest requested changes

2023-04-28 07:32 UTC, indiest commented on Source/ChanneldEditor/ChanneldEditorCommands.cpp
> +	UI_COMMAND(ToggleCompatibleRecompilationCommand, "Enable Compatible Recompilation", "Turn on to enable recompilation after generating replication code", EUserInterfaceActionType::ToggleButton, FInpu
```suggestion
	UI_COMMAND(ToggleCompatibleRecompilationCommand, "Enable Compatible Recompilation", "Turn on to enable recompilation and hot-reload after generating replication code", EUserInterfaceActionType::ToggleButton, FInputChord());
```

2023-04-28 07:47 UTC, indiest approved these changes

2023-04-28 07:48 UTC, merged