Recommended workflow document
metaworking/channeld-ue-plugin pull request #16
Opened 2023-04-24 05:42 UTC by Augkit

2023-04-30 07:39 UTC, indiest commented on Docs/zh/recommended-workflow.md
>  ### 使用UE原生网络同步开发
```suggestion
### 使用原生UE进行开发迭代
```

2023-04-30 07:42 UTC, indiest commented on Docs/zh/recommended-workflow.md
> +开发过程推荐优先使用[UE原生网络同步](https://docs.unrealengine.com/4.27/zh-CN/InteractiveExperiences/Networking/Actors/)进行GamePlay的开发和调试。在实现GamePlay功能后再开启ChanneldUE网络同步进行开发和调试。这样可以避免频繁地生成同步代码、启动专用服务器和网关。
```suggestion
在日常的开发中，推荐先使用
[UE原生网络同步](https://docs.unrealengine.com/4.27/zh-CN/InteractiveExperiences/Networking/Actors/)进行玩法的开发迭代。在完成阶段性迭代后，再开启ChanneldUE网络同步进行测试。这样可以避免频繁地生成同步代码、重启channeld网关和专用服务器。
```

2023-04-30 07:45 UTC, indiest commented on Docs/zh/recommended-workflow.md
> +当实现了GamePlay功能并测试完成后，就可以使用ChanneldUE的网络同步来进行测试。
```suggestion
```

2023-04-30 07:45 UTC, indiest commented on Docs/zh/recommended-workflow.md
> +#### 开启ChanneldUE网络同步
```suggestion
```

2023-04-30 07:46 UTC, indiest commented on Docs/zh/recommended-workflow.md
>  #### 为Actor开启同步功能
```suggestion
#### 为Actor开启基于ChanneldUE的同步
```

2023-04-30 07:49 UTC, indiest commented on Docs/zh/recommended-workflow.md
> +在UE原生网络同步配置的基础上还需要为Actor添加同步组件。ChannelUE支持为C++和蓝图Actor添加同步组件。具体操作如下：
```suggestion
使用了网络同步或RPC的Actor需要添加同步组件。具体操作如下：
```

2023-04-30 07:49 UTC, indiest commented on Docs/zh/recommended-workflow.md
>      ![](../images/character_rep_component.png)
```suggestion

![](../images/character_rep_component.png)
```

2023-04-30 07:51 UTC, indiest commented on Docs/zh/recommended-workflow.md
> +##### 为已有项目的同步Actor添加同步组件
```suggestion
##### 批量添加同步组件
```

2023-04-30 07:56 UTC, indiest commented on Docs/zh/recommended-workflow.md
>  为同步Actor添加同步组件后还不足以使他们通过ChanneldUE同步，还需指定同步Actor的状态在哪个频道中同步。ChanneldUE通过频道数据模型来指定同步Actor的状态在哪个频道中同步。
```suggestion
为同步Actor添加同步组件后，还需要配置频道数据模型来映射同步Actor和频道数据的关系。
```

2023-04-30 07:56 UTC, indiest commented on Docs/zh/recommended-workflow.md
> +##### 打开频道数据模型编辑器
```suggestion
```

2023-04-30 07:56 UTC, indiest commented on Docs/zh/recommended-workflow.md
> +频道数据模型需要在频道数据模型编辑器中进行配置。点击ChannelUE插件的`Editor Channel Data Schema` 按钮：
```suggestion
点击ChannelUE插件的`Editor Channel Data Schema` 按钮：
```

2023-04-30 07:58 UTC, indiest commented on Docs/zh/recommended-workflow.md
> +首先，需要更新同步Actor缓存。在频道数据编辑器上方点击`Refresh...`按钮：
```suggestion
首先，如果同步缓存过期（出现黄色叹号），需要先对其进行更新。在频道数据编辑器上方点击`Refresh...`按钮：
```

2023-04-30 08:01 UTC, indiest commented on Docs/zh/recommended-workflow.md
> +除手动为同步Actor添加同步组件外，ChanneldUE提供了工具为已有项目中的Actor添加同步组件：
```suggestion
除手动为同步Actor添加同步组件外，ChanneldUE提供了工具为当前项目中的所有同步Actor批量添加同步组件：
```

2023-04-30 08:04 UTC, indiest commented on Docs/zh/recommended-workflow.md
>  等待同步Actor缓存更新完成后，就可以将新增的同步Actor状态添加到某一个频道数据下：
```suggestion
同步缓存更新完成后，将新增的同步Actor映射到某一个频道数据下：（下图演示将`BP_TestRep`映射到全局频道。因为`BP_TestRep`依赖`StaticMeshComponent`组件，所以该组件也被同时添加到全局频道）
```

2023-04-30 08:06 UTC, indiest commented on Docs/zh/recommended-workflow.md
> +##### 生成
```suggestion
```

2023-04-30 08:07 UTC, indiest commented on Docs/zh/recommended-workflow.md
>  配置完成频道数据模型后，需要生成C++的同步代码。同步代码主要是用来处理频道数据模型的状态同步的。
```suggestion
配置完成频道数据模型后，需要生成C++的同步代码。同步代码主要是用来实现频道数据模型中的状态同步。
```

2023-04-30 08:10 UTC, indiest commented on Docs/zh/recommended-workflow.md
>  ChannelUE提供了热编译兼容模式，该模式下每次生成同步代码后自动热编译项目源码，如果关闭热编译兼容模式则在生成同步代码后需要先关闭UE编辑器再通过源码编译。
```suggestion
ChannelUE提供了热编译兼容模式，该模式下每次生成同步代码后自动热编译项目源码。如果关闭了热编译兼容模式，在下次运行游戏前，需要关闭UE编辑器并重新编译项目代码。
```

2023-04-30 08:12 UTC, indiest commented on Docs/zh/recommended-workflow.md
> +由于ChanneldUE采用了分布式专用服务器的架构，所以在本地测试时需要启动多个专用服务器和网关。ChannelUE提供了专用服务器和网关的启动工具。
```suggestion
由于ChanneldUE采用了分布式专用服务器的架构，所以在本地测试时需要启动channeld网关和多个专用服务器。ChanneldUE提供了相关的启动工具。
```

2023-04-30 08:13 UTC, indiest commented on Docs/zh/recommended-workflow.md
> +#### 启动专用服务器和网关
```suggestion
#### 启动网关和专用服务器
```

2023-04-30 08:13 UTC, indiest commented on Docs/zh/recommended-workflow.md
> +通过插件的二级菜单开启专用服务器和网关，步骤如下：
```suggestion
通过插件的下拉菜单开启网关和专用服务器，步骤如下：
```

2023-04-30 08:17 UTC, indiest commented on Docs/zh/recommended-workflow.md
> +频道数据模型定义文件建议通过版本控制工具进行版本控制，以保证多人协作时频道数据模型的一致性。频道数据模型定义文件路径为`Config/ChanneldChannelDataSchema.json`。
```suggestion
频道数据模型定义文件建议通过版本控制工具进行版本控制，以保证多人协作时，生成的同步代码是一致的。频道数据模型定义文件路径为`Config/ChanneldChannelDataSchema.json`。
```

2023-04-30 08:18 UTC, indiest commented on Docs/zh/recommended-workflow.md
> +2. [生成一次同步代码](#生成同步代码)
我记得在生成同步代码时，会先删除ChanneldGenerated文件，对吗？

2023-04-30 08:20 UTC, indiest commented on Docs/zh/recommended-workflow.md
> +#### 无需上传至版本控制
生成的go代码，哪些需要添加版本控制，哪些需要忽略？

2023-05-04 08:10 UTC, Augkit commented on Docs/zh/recommended-workflow.md
> +2. [生成一次同步代码](#生成同步代码)
之所以建议手动删除是因为通过版本控制更新了c++的同步actor可能会导致编译不过

2023-05-04 08:16 UTC, Augkit commented on Docs/zh/recommended-workflow.md
> +#### 无需上传至版本控制
通常来说Go的代码是跟随channeld的，channeld又不上传到版本控制。不过可以提一下如果开发者使用自己版本的channeld，那可以[参考channeld的gitignore](https://github.com/metaworking/channeld/blob/master/.gitignore)

2023-05-04 08:30 UTC, Augkit commented on Docs/zh/recommended-workflow.md
>      ![](../images/character_rep_component.png)
此处需要一个缩进来使（* 为蓝图Actor中添加同步组件）下的图片对齐

2023-05-06 01:46 UTC, indiest commented on Docs/zh/recommended-workflow.md
> +2. [生成一次同步代码](#生成同步代码)
如果在编译前，先自动删除ChanneldGenerated文件夹，再重新生成，为什么会导致编译不通过？

2023-05-06 01:47 UTC, indiest commented on Docs/zh/recommended-workflow.md
> +#### 无需上传至版本控制
意思是说生成的go代码，全部都不需要添加到版本控制？

2023-05-06 01:54 UTC, indiest commented on Docs/zh/recommended-workflow.md
> +开发过程推荐优先使用[UE原生网络同步](https://docs.unrealengine.com/4.27/zh-CN/InteractiveExperiences/Networking/Actors/)进行GamePlay的开发和调试。在实现GamePlay功能后再开启ChanneldUE网络同步进行开发和调试。这样可以避免频繁地生成同步代码、启动专用服务器和网关。
现在文档中还存在两个`GamePlay`，请替换成`玩法`

2023-05-06 01:56 UTC, indiest commented on Docs/zh/recommended-workflow.md
> +    1. Actor 类中声明`ChanneldReplicationComponent`组件
```suggestion
    1. Actor 类中声明`ChanneldReplicationComponent`组件：
```

2023-05-06 01:56 UTC, indiest commented on Docs/zh/recommended-workflow.md
> +    2. Actor 的构造函数中实例化`ChanneldReplicationComponent`组件
```suggestion
    2. Actor 的构造函数中实例化`ChanneldReplicationComponent`组件：
```

2023-05-06 01:57 UTC, indiest commented on Docs/zh/recommended-workflow.md
> +>注意：该工具会加载项目中所有的Actor，如果项目中有大量的Actor，可能会导致加载时间过长，建议在仅在项目中途才使用ChanneldUE插件时使用一次该功能或者较小项目中使用该功能。
```suggestion
>注意：该工具会加载项目中所有的Actor，如果项目中有大量的Actor，可能会导致加载时间过长。
```

2023-05-06 01:59 UTC, indiest commented on Docs/zh/recommended-workflow.md
> +>cmd/gen_proto.*
什么情况下会生成这种文件？

2023-05-15 12:42 UTC, Augkit commented on Docs/zh/recommended-workflow.md
> +2. [生成一次同步代码](#生成同步代码)
更新代码时Editor没有着，然后更新的代码修改现有c++的类导致了之前生成的同步代码报错了，那Editor就会因为编译问题启动不了，也就没法通过Editor去重新生成代码了

2023-05-15 12:44 UTC, Augkit commented on Docs/zh/recommended-workflow.md
> +#### 无需上传至版本控制
是的

2023-05-15 13:08 UTC, Augkit commented on Docs/zh/recommended-workflow.md
> +#### 无需上传至版本控制
为了兼容UE热编译所以每次生成的proto名字都不相同，并且生成的go代码只有channeldue.gen.go和channeldgenpb，channeldue.gen.go使用了channeldgenpb，应当都被忽略

2023-05-17 01:55 UTC, indiest commented on Docs/zh/recommended-workflow.md
> +2. [生成一次同步代码](#生成同步代码)
需要在130行说明UE编辑器打开或关闭的情况下更新代码后，分别需要做什么操作

2023-05-17 01:55 UTC, indiest requested changes
需要在130行说明UE编辑器打开或关闭的情况下更新代码后，分别需要做什么操作

2023-05-18 01:49 UTC, indiest requested changes
见批注

2023-05-18 01:49 UTC, indiest commented on Docs/zh/recommended-workflow.md
> +2. [生成一次同步代码](#生成同步代码)
```suggestion
2. 编译并运行项目
3. [生成同步代码](#生成同步代码)
```

2023-05-18 01:49 UTC, indiest commented on Docs/zh/recommended-workflow.md
> +1. 如果更新了C++的同步Actor建议先手动删除位于`Source/<游戏模块>/ChanneldGenerated`目录下的文件，确保能够顺利编译
```suggestion
1. 手动删除位于`Source/<游戏模块>/ChanneldGenerated`目录下的文件
```

2023-05-18 01:49 UTC, indiest commented on Docs/zh/recommended-workflow.md
> +在UE编辑器**未开启**时通过版本控制变更了项目代码，建议执行如下操作：
```suggestion
在UE编辑器**未开启**时，通过版本控制更新了项目代码，建议执行如下操作：
```

2023-05-18 01:49 UTC, indiest commented on Docs/zh/recommended-workflow.md
> +在UE编辑器**已开启**时通过版本控制变更了项目代码，建议执行如下操作：
```suggestion
在UE编辑器**已开启**时，通过版本控制更新了项目代码后，需要重新[生成同步代码](#生成同步代码)。
```

2023-05-18 01:49 UTC, indiest commented on Docs/zh/recommended-workflow.md
> +1. [生成一次同步代码](#生成同步代码)
```suggestion
```

2023-05-18 01:49 UTC, indiest commented on Docs/zh/recommended-workflow.md
> +>如使用git作为版本控制工具，可以在项目根目录下的`.git/hooks/post-merge`脚本中添加删除`Source/<游戏模块>/ChanneldGenerated`目录的逻辑。
这个提示建议加到“UE编辑器未开启”那一段的后面

2023-05-23 02:50 UTC, indiest approved these changes

2023-05-23 02:51 UTC, merged