Ue5 compile fix
metaworking/channeld-ue-plugin pull request #57
Opened 2023-08-10 06:10 UTC by ganibc

- Add UE5 compatible UI and platform settings code
- Use original cookcommandlet
- Change ReplicatorGenerator LoadingPhase to PostConfig
  Cook requires PRIVATE_GIsRunningCookCommandlet to be true
  Must be set before AssetRegistry loaded
  Without this, it will stuck
  Set PRIVATE_GIsRunningCookCommandlet in ReplicatorGenerator.cpp

2023-08-10 09:28 UTC, indiest commented
Thanks for the contribution!

Have you tested the compatibility with UE 4.27.2? If not, I will do that soon.

Also, does the replication codegen work for you with this fix? If not, I would suggest you take a look at the `ue-5.1` branch in which the related issues are fixed.

2023-08-11 00:27 UTC, ganibc commented
I haven't tried with UE4.
Unless I'm making mistake on the `#if` statements, then it shouldn't change any logic on UE4.
The code generation is working fine.

2023-08-11 01:53 UTC, indiest commented
> Is the changes mergeable to the master branch? 

Yes, it's mergeable.

> Any reason why it's not merged to master branch yet?

It will be soon. We are planning to release the support of UE5 in the next millestone (v0.7).

2023-08-11 02:51 UTC, indiest commented on ChanneldUE.uplugin
> +      "LoadingPhase": "PostConfigInit"
Is there a particular reason to change the loading phase? It breaks `UChanneldEditorSubsystem::NeedToGenerateReplicationCode` in UE 4.27.2 as the `UChannelDataSchemaController` editor subsystem is not loaded.

2023-08-11 02:53 UTC, indiest commented on Source/ChanneldEditor/ChanneldEditorSubsystem.cpp
> +#include "Settings/PlatformsMenuSettings.h"
```suggestion
#if ENGINE_MAJOR_VERSION >= 5
#include "Settings/PlatformsMenuSettings.h"
#endif
```

2023-08-11 03:03 UTC, indiest requested changes
Fixed the compilation errors on UE 4.27.2.

2023-08-11 03:34 UTC, ganibc commented on ChanneldUE.uplugin
> +      "LoadingPhase": "PostConfigInit"
As I put in the description, Cook requires PRIVATE_GIsRunningCookCommandlet to be true and this need to happened before AssetRegistry module loaded.
If not, then it will stuck.

When `NeedToGenerateReplicationCode` is called? I'm not sure how it get affected with the changing the loading phase of ReplicatorGenerator

2023-08-11 03:40 UTC, ganibc commented on Source/ChanneldEditor/ChanneldEditorSubsystem.cpp
> +	while (PlatformInfo != PlatformInfo->VanillaInfo)
The vanilla platform name is not immediately available in the FTargetPlatformInfo, but we have to access to VanillaInfo. The documentation doesn't mention that it will be single level, so loop might be required.
https://docs.unrealengine.com/5.1/en-US/API/Developer/DesktopPlatform/FTargetPlatformInfo/
![image](https://github.com/metaworking/channeld-ue-plugin/assets/1264707/5536f57f-90fc-417f-8afd-1262b92df0c5)

2023-08-11 03:51 UTC, ganibc commented on Source/ChanneldEditor/ChanneldEditorSubsystem.cpp
> +	FName VanillaPlatformName = PlatformInfo->Name;
Changes commited.

2023-08-11 08:14 UTC, indiest commented on ChanneldUE.uplugin
> +      "LoadingPhase": "PostConfigInit"
Changing the LoadingPhase to `PostConfigInit` causes this line to fail when loading the `ReplicatorGenerator` module:

![image](https://github.com/metaworking/channeld-ue-plugin/assets/5010912/4e5ac6e1-a3d9-4146-be84-3bed9b6f2c3e)

2023-08-11 08:28 UTC, indiest commented on Source/ChanneldEditor/ChanneldEditorSubsystem.cpp
> +	while (PlatformInfo != PlatformInfo->VanillaInfo)
If the VanillaInfo could be nested, maybe you should the loop sholud look like this?
```cpp
	while (PlatformInfo != PlatformInfo->VanillaInfo)
	{
		PlatformInfo = PlatformInfo->VanillaInfo;
		VanillaPlatformName = PlatformInfo->Name;
	}
```

2023-08-11 08:39 UTC, ganibc commented on Source/ChanneldEditor/ChanneldEditorSubsystem.cpp
> +	while (PlatformInfo != PlatformInfo->VanillaInfo)
You are correct. I thought I did this.

2023-08-11 08:44 UTC, ganibc commented on Source/ChanneldEditor/ChanneldEditorSubsystem.cpp
> +	while (PlatformInfo != PlatformInfo->VanillaInfo)
Fixed.

2023-08-11 09:08 UTC, indiest commented on ChanneldUE.uplugin
> +      "LoadingPhase": "PostConfigInit"
Tested `PreDefault` LoadingPhase and it works for UE 4.27.2. @ganibc could you please try with UE 5.2 too?

2023-08-14 01:00 UTC, ganibc commented on ChanneldUE.uplugin
> +      "LoadingPhase": "PostConfigInit"
It doesn't work on 5.2. 
AssetRegistry module is already loaded at PreDefault.
I will debug a bit deeper to find out why AssetRegistry loaded without `PRIVATE_GIsRunningCookCommandlet` set to true will freeze the commandlet.

By the way, in 5.2 the code you snapshot is the basically the same, but the ensure is disabled for commandlet.

![devenv_jZQR1DCRGw](https://github.com/metaworking/channeld-ue-plugin/assets/1264707/019abe53-094e-472a-a3e6-3c0a232dd58a)

2023-08-14 01:53 UTC, ganibc commented on ChanneldUE.uplugin
> +      "LoadingPhase": "PostConfigInit"
I've reverted the LoadingPhase changes.
I can use -AssetGatherAll=true in the argument to prevent this problem. 
Please have a look

2023-08-14 09:37 UTC, indiest approved these changes
LGTM

2023-08-14 09:40 UTC, merged